136 intuitive frontend interface for pipeline definition
swiss-ai-center/core-engine pull request #206
Opened 2024-03-17 11:02 UTC by Gaetan-cogliati

Interactive pipeline creation feature

2024-04-08 07:23 UTC, andrptrc requested changes
Generally, try to lint/format the code when you write it (Cmd+opt+L on mac in WebStorm) so it is easier to read. Will discuss with you about some other improvements in the next meeting

2024-04-08 07:23 UTC, andrptrc commented on frontend/src/components/CardBase/CardBase.tsx
> +        <Grid xs={12} sm={6} lg={4} xl={3} key={index}
If the component is called CardBase, it should only be about a Card item, not a Grid of Cards, maybe use CardBase in a ItemGridBase or something similar

2024-04-08 07:23 UTC, andrptrc commented on frontend/src/enums/dataTypeEnum.tsx
> +Object.values(DataType).forEach((value) => {
Why do we need to add this to an array to export ?

2024-04-08 07:23 UTC, andrptrc commented on frontend/src/enums/dataTypeEnum.tsx
> +// each tag has an acronym, name, and a unique set of colors
Is this comment correct ?

2024-04-22 13:41 UTC, andrptrc requested changes
Also look at the following points:

- The file structure can be improved. For example put the cards in a `Cards` folder just like nodes, the point here is to be constant on the structure every where
- Check logs and remove every unused import or variable also checks for linting warnings
- Edit Nodes design could be improved to look a little more like the “non-editable” nodes
- Select-boxes style to match with other components and Board dimensions, settings, placing and spacing on page too
- Code improvements and bug fixing
- Code formatting (Cmd + alt + L on WebStorm)

2024-04-22 13:41 UTC, andrptrc commented on frontend/src/components/ServiceCard/HomeServiceCard.tsx
> +                <Button size={"small"} variant={"contained"}>View</Button>
add `disableElevation` to button (basically do it on every button that variant is not outlined

2024-04-22 13:41 UTC, andrptrc commented on frontend/src/components/ItemGrid/PipelineList.tsx
> +                                                <Button size={"small"} variant={"contained"}>View</Button>
Also add `disableElevation` here

2024-04-22 13:41 UTC, andrptrc commented on frontend/src/components/Edges/EditEdge.tsx
Add background or another way to improve visibility of condition. Perhaps putting the edge z index on top of everything else could improve this

2024-04-22 13:41 UTC, andrptrc commented on frontend/src/components/ItemGrid/PipelineList.tsx
Why is there a pipelineList but no serviceList component ? Is this file used ? Maybe adapt it and create the service one and include them in the code of other components

2024-04-22 13:41 UTC, andrptrc commented on frontend/src/enums/dataTypeEnum.tsx
> + export const DataTypeOptions: string[] = [];
maybe change uppercase first letter to lower case

2024-04-22 13:41 UTC, andrptrc commented on frontend/src/pages/Showcase/index.tsx
> +
Useless blank lines

2024-04-22 13:41 UTC, andrptrc commented on frontend/src/utils/api.tsx
> +    const headers = {
Are these headers mandatory ? or could we use the const variable on top of the file ?

2024-04-22 13:41 UTC, andrptrc commented on frontend/src/utils/api.tsx
> +        'Access-Control-Allow-Origin': '*',
Same here

2024-04-22 13:41 UTC, andrptrc commented on frontend/src/pages/CreatePipeline/index.tsx
> +    }, []);
Either add dependencies to the array or remove it, but empty arrays should be avoided

2024-04-22 13:41 UTC, andrptrc commented on frontend/src/pages/CreatePipeline/index.tsx
> +            const node = nodesRef.current.find((nd) => nd.id === queue[index])
ESLint: Function declared in a loop contains unsafe references to variable(s) 'index'.(no-loop-func)

2024-04-22 13:41 UTC, andrptrc commented on frontend/src/pages/CreatePipeline/index.tsx
> +        while (nodesRef.current.find((node) => node.data.identifier === identifier)) {
ESLint: Function declared in a loop contains unsafe references to variable(s) 'index'.(no-loop-func)

2024-04-22 13:41 UTC, andrptrc commented on frontend/src/pages/CreatePipeline/index.tsx
> +    const onConnect = (params: Edge<any> | Connection) => {
Explicit type argument any can be removed

2024-04-22 13:54 UTC, andrptrc commented
Some more comments:

- How do we see the JSON result? Maybe a non-editable text-box like the one for the description on showcase page
- Try putting Service Cards in the sidebar
- When you link input to end -> error
- Unique key on each element (check error logs in browser
- Adapt the spacinf of fields for editing descriptions and other pipeline info to be the same as other parts of the website

2024-05-16 19:57 UTC, Gaetan-cogliati commented
Elements to improve, add or fix:
- Find a way to let child nodes change the state of the 'nodes' and 'edges' state variables from the CreatePipeline page without having to use Refs (that need to be updated in a useEffect or useMemo).
- Put the service list in the sidebar
- Maybe restrict the selection of input types to compatible ones only, once the input handle is connected.
- Make sure the order of the pipeline inputs is correct in the generated JSON (pipeline description).
- Find a way to conveniently show the generated JSON to the user.

2024-06-11 10:05 UTC, andrptrc approved these changes

2024-06-11 12:45 UTC, rmarquis approved these changes

2024-06-11 12:47 UTC, rmarquis commented
Looks okay to me.

I see some warning in the frontend section though. I don't know if these are related to this PR or if that's an older issue:

```
WARNING in [eslint]
frontend  | src/components/FilterDrawer/FilterDrawer.tsx
frontend  |   Line 63:11:  'MaterialUISwitch' is assigned a value but never used  @typescript-eslint/no-unused-vars
frontend  |   Line 99:11:  'CustomSwitch' is assigned a value but never used      @typescript-eslint/no-unused-vars
frontend  |
frontend  | src/pages/PipelineEditor/index.tsx
frontend  |   Line 614:8:  React Hook React.useEffect has a missing dependency: 'onEdgeDelete'. Either include it or remove the dependency array  react-hooks/exhaustive-deps
```

Also some deprecation warnings:
```
(node:37) [DEP_WEBPACK_DEV_SERVER_ON_AFTER_SETUP_MIDDLEWARE] DeprecationWarning: 'onAfterSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
frontend  | (Use `node --trace-deprecation ...` to show where the warning was created)
frontend  | (node:37) [DEP_WEBPACK_DEV_SERVER_ON_BEFORE_SETUP_MIDDLEWARE] DeprecationWarning: 'onBeforeSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
```

2024-06-12 08:39 UTC, merged